INIGrammar : 
    Grammar <- Statement*
    Statement <- Section / Comment
    Comment <- "#" (!:endOfLine)* :endOfLine
    Section <- SectionHead (Declaration)*
    SectionHead <- :"[" SectionIdentifier :"]" ( :endOfLine / endOfInput )
    SectionIdentifier <- identifier ( :"." identifier)?
    Declaration <- identifier :"=" Literal ( :endOfLine / endOfInput )
    Literal <- BasicElements.String /  BasicElements.Numeric / BasicElements.Bool
